products = [
    {'id': 1, 'name': 'Wurood', 'price': '2999', 'category': 'Premium Fragrance', 'image': 'assets/images/wurood-rs-2999.jpeg'},
    {'id': 2, 'name': 'Black Scent', 'price': '1899', 'category': 'Premium Fragrance', 'image': 'assets/images/black-scent-rs-1899.jpeg'},
    {'id': 3, 'name': 'ROMANCE', 'price': '2999', 'category': 'Premium Fragrance', 'image': 'assets/images/romance-2999.jpeg'},
    {'id': 4, 'name': 'Tiger Black', 'price': '1799', 'category': 'Premium Fragrance', 'image': 'assets/images/tiger-black-rs-1799.jpeg'},
    {'id': 5, 'name': 'AL-WATANI', 'price': '1799', 'category': 'Premium Fragrance', 'image': 'assets/images/al-watani-rs-1799.jpeg'},
    {'id': 6, 'name': 'Noble Man', 'price': '1999', 'category': 'Premium Fragrance', 'image': 'assets/images/noble-man-rs-1999.jpeg'},
    {'id': 7, 'name': 'DIVINE', 'price': '1699', 'category': 'Premium Fragrance', 'image': 'assets/images/divine-rs-1699.jpeg'},
    {'id': 8, 'name': 'HISTORY', 'price': '2499', 'category': 'Premium Fragrance', 'image': 'assets/images/history-rs-2499.jpeg'},
    {'id': 9, 'name': 'MAXI', 'price': '4999', 'category': 'Premium Fragrance', 'image': 'assets/images/maxi-rs-4999.jpeg'},
    {'id': 10, 'name': 'NTA By BLAZER', 'price': '1599', 'category': 'Premium Fragrance', 'image': 'assets/images/nta-by-blazer-rs-1599.jpeg'},
    {'id': 11, 'name': 'TEA ROSE MESK', 'price': '1999', 'category': 'Premium Fragrance', 'image': 'assets/images/tea-rose-mesk-rs-1999.jpeg'},
    {'id': 12, 'name': 'MUSK AL-HAWAMEER', 'price': '2499', 'category': 'Premium Fragrance', 'image': 'assets/images/musk-al-hawameer-rs-2499.jpeg'},
    {'id': 13, 'name': 'NAJOOM', 'price': '1699', 'category': 'Premium Fragrance', 'image': 'assets/images/najoom-rs-1699.jpeg'},
    {'id': 14, 'name': 'MARQUIS', 'price': '3799', 'category': 'Premium Fragrance', 'image': 'assets/images/marquis-rs-3799.jpeg'},
    {'id': 15, 'name': 'KHUMAR', 'price': '4499', 'category': 'Premium Fragrance', 'image': 'assets/images/khumaar-rs-4499.jpeg'},
    {'id': 16, 'name': 'JANAN SPORT By J.', 'price': '6299', 'category': 'Premium Fragrance', 'image': 'assets/images/janan-sports-by-j.-rs-6299.jpeg'},
    {'id': 17, 'name': 'JANAN OUD By J.', 'price': '6299', 'category': 'Premium Fragrance', 'image': 'assets/images/janan-oud-by-j.-rs-6299.jpeg'},
    {'id': 18, 'name': 'WHITE MUSK BY J.', 'price': '4999', 'category': 'Premium Fragrance', 'image': 'assets/images/white-musk-rs-4999.jpeg'},
    {'id': 19, 'name': 'MARJ By AHMED AL-MAGHRABI', 'price': '13999', 'category': 'Premium Fragrance', 'image': 'assets/images/marj-by-ahmed-al-maghrabi-rs-13999.jpeg'},
    {'id': 20, 'name': 'KAAF', 'price': '6999', 'category': 'Premium Fragrance', 'image': 'assets/images/kaaf-rs-699.jpeg'},
    {'id': 21, 'name': 'Blue Lady', 'price': '2999', 'category': 'Premium Fragrance', 'image': 'assets/images/blue-lady-rs-2999.jpeg'},
    {'id': 22, 'name': 'AL-FARAS', 'price': '3499', 'category': 'Premium Fragrance', 'image': 'assets/images/al-faras-rs3499.jpeg'},
    {'id': 23, 'name': 'LAMSAT HARIR', 'price': '2999', 'category': 'Premium Fragrance', 'image': 'assets/images/lamsat-harir-rs--2999.jpeg'},
    {'id': 24, 'name': 'MOUSOF', 'price': '3999', 'category': 'Premium Fragrance', 'image': 'assets/images/mousof-rs-3999.jpeg'},
    {'id': 25, 'name': 'OUD HAYAT', 'price': '2999', 'category': 'Premium Fragrance', 'image': 'assets/images/oud-hayat-rs-2999.jpeg'},
    {'id': 26, 'name': 'UROOSA By J.', 'price': '3499', 'category': 'Premium Fragrance', 'image': 'assets/images/uroosa-by-j.-rs-3499.jpeg'},
    {'id': 27, 'name': 'Wurood 4 by Rasasi', 'price': '4499', 'category': 'Premium Fragrance', 'image': 'assets/images/wardat-4-by-rasasi-rs-4499.jpeg'},
    {'id': 28, 'name': 'Musk Silk Ajmal', 'price': '4999', 'category': 'Attar', 'image': 'assets/images/musk-silk-ajmal-rs-4999.jpeg'},
    {'id': 29, 'name': 'Applause', 'price': '2999', 'category': 'Attar', 'image': 'assets/images/applause-12ml-rs-2999.jpeg'},
    {'id': 30, 'name': 'Ashwaaq', 'price': '2599', 'category': 'Attar', 'image': 'assets/images/ashwaaq-12ml-rs-2599.jpeg'},
    {'id': 31, 'name': 'Lucky', 'price': '2799', 'category': 'Attar', 'image': 'assets/images/lucky-12ml-rs-2799.jpeg'},
    {'id': 32, 'name': 'Malika', 'price': '3599', 'category': 'Attar', 'image': 'assets/images/malika-12ml-rs-3599.jpeg'},
    {'id': 33, 'name': 'Musk Rose', 'price': '3499', 'category': 'Attar', 'image': 'assets/images/musk-rose-12ml-rs-3499.jpeg'},
    {'id': 34, 'name': 'Oud E Aswad', 'price': '5999', 'category': 'Attar', 'image': 'assets/images/oud-e-aswad-12ml-rs-5999.jpeg'},
    {'id': 35, 'name': 'Oudh O Oudh', 'price': '3999', 'category': 'Attar', 'image': 'assets/images/oudh-o-oudh-12ml-rs-3999.jpeg'},
    {'id': 36, 'name': 'Sweet Oud', 'price': '3499', 'category': 'Attar', 'image': 'assets/images/sweet-oud-12ml-rs-3499.jpeg'},
    {'id': 37, 'name': 'Ward No 1', 'price': '1599', 'category': 'Attar', 'image': 'assets/images/ward-no1-12ml-rs-1599.jpeg'},
    {'id': 38, 'name': 'Ward E Khaas', 'price': '1999', 'category': 'Attar', 'image': 'assets/images/ward-e-khaas-12ml-rs1999.jpeg'},
    {'id': 39, 'name': 'Amber Oud', 'price': '3499', 'category': 'Attar', 'image': 'assets/images/amber-oud-by-surrati-rs-3499.jpeg'},
    {'id': 40, 'name': 'Banafsaji', 'price': '3499', 'category': 'Attar', 'image': 'assets/images/banafsaji-by-surrati-rs-3499.jpeg'},
    {'id': 41, 'name': 'Black Oud', 'price': '3499', 'category': 'Attar', 'image': 'assets/images/black-oud-by-surrati-rs-3499.jpeg'},
    {'id': 42, 'name': 'Dehan Oud Ateeq', 'price': '5999', 'category': 'Attar', 'image': 'assets/images/dehan-oud-ateeq-by-surrati-rs-5999.jpeg'},
    {'id': 43, 'name': 'Musk Al-Bait', 'price': '5999', 'category': 'Attar', 'image': 'assets/images/musk-al-bait-by-surrati-rs-5999.jpeg'},
    {'id': 44, 'name': 'White Oud', 'price': '3499', 'category': 'Attar', 'image': 'assets/images/white-oud-by-surrati-rs-3499.jpeg'},
    {'id': 45, 'name': 'Afnan Premium', 'price': '2799', 'category': 'Afnan', 'image': 'assets/images/afnan.jpeg'},
    {'id': 46, 'name': 'Dehan Al-Oud Abiyad', 'price': '2799', 'category': 'Afnan', 'image': 'assets/images/dehan-al-oud-abiyad-rs-by-afnan-rs-2799.jpeg'},
    {'id': 47, 'name': 'Mukhallat Abiyad', 'price': '2799', 'category': 'Afnan', 'image': 'assets/images/mukhallat-abiyad-by-afnan-rs-2799.jpeg'},
    {'id': 48, 'name': 'Musk Abiyad', 'price': '2799', 'category': 'Afnan', 'image': 'assets/images/musk-abiyad-by-afnan-rs-2799.jpeg'},
    {'id': 49, 'name': 'Alifun Lailatun Wa Lailah', 'price': '2799', 'category': 'Attar', 'image': 'assets/images/alifun-lailatun--wa-lailah-12ml-rs-2799.jpeg'},
    {'id': 50, 'name': 'Ameer Ul Oud', 'price': '1499', 'category': 'Attar', 'image': 'assets/images/ameer-ul-oud-12ml-rs-1499.jpeg'},
    {'id': 51, 'name': 'Aventus Creed', 'price': '1699', 'category': 'Attar', 'image': 'assets/images/aventus-creed-12ml-rs-1699.jpeg'},
    {'id': 52, 'name': 'Bad E Saba', 'price': '1599', 'category': 'Attar', 'image': 'assets/images/bad-e-saba-12ml-rs-1599.jpeg'},
    {'id': 53, 'name': 'Bakarat', 'price': '1599', 'category': 'Attar', 'image': 'assets/images/bakarat-12ml-rs-1599.jpeg'},
    {'id': 54, 'name': 'Dehan Oud Combodi', 'price': '7999', 'category': 'Attar', 'image': 'assets/images/dehan-oud-combodi-12ml-rs-7999.jpeg'},
    {'id': 55, 'name': 'David Beckham', 'price': '1599', 'category': 'Attar', 'image': 'assets/images/david-beckham-12ml-rs-1599.jpeg'},
    {'id': 56, 'name': 'Ehsaas', 'price': '1399', 'category': 'Attar', 'image': 'assets/images/ehsaas-12ml-rs-1399.jpeg'},
    {'id': 57, 'name': 'Fogg', 'price': '1499', 'category': 'Attar', 'image': 'assets/images/fogg-12ml-rs-1499.jpeg'},
    {'id': 58, 'name': 'Gucci Flora', 'price': '1099', 'category': 'Attar', 'image': 'assets/images/gucci-flora-12ml-rs-1099.jpeg'},
    {'id': 59, 'name': 'Husn E Yousuf', 'price': '1599', 'category': 'Attar', 'image': 'assets/images/husn-e-yousuf-12ml-rs-1599.jpeg'},
    {'id': 60, 'name': 'Janan Sports', 'price': '1499', 'category': 'Attar', 'image': 'assets/images/janan-sports-12ml-rs-1499.jpeg'},
    {'id': 61, 'name': 'Khas Special', 'price': '5999', 'category': 'Attar', 'image': 'assets/images/khas-special-12ml-rs-5999.jpeg'},
    {'id': 62, 'name': 'Marj', 'price': '1699', 'category': 'Attar', 'image': 'assets/images/marj-12ml-rs-1699-(2).jpeg'},
    {'id': 63, 'name': 'Mukhallat Oud Rose', 'price': '2399', 'category': 'Attar', 'image': 'assets/images/mukhallat-oud-rose-12ml-rs-2399.jpeg'},
    {'id': 64, 'name': 'Mukhallat Oud', 'price': '2799', 'category': 'Attar', 'image': 'assets/images/mukhallat-oud--rs-2799.jpeg'},
    {'id': 65, 'name': 'Office Man', 'price': '1999', 'category': 'Attar', 'image': 'assets/images/office-man-12ml-rs-1999.jpeg'},
    {'id': 66, 'name': 'One Man Show', 'price': '999', 'category': 'Attar', 'image': 'assets/images/one-man-show-12ml-rs-999.jpeg'},
    {'id': 67, 'name': 'Oud Asfahan', 'price': '1799', 'category': 'Attar', 'image': 'assets/images/oud-asfahan-12ml-rs-1799.jpeg'},
    {'id': 68, 'name': 'Oud Mood', 'price': '3799', 'category': 'Attar', 'image': 'assets/images/oud-mood-12ml-rs-3799.jpeg'},
    {'id': 69, 'name': 'Oud for Greatness', 'price': '1599', 'category': 'Attar', 'image': 'assets/images/oud-for-greatness-12ml-rs-1599.jpeg'},
    {'id': 70, 'name': 'Qissa', 'price': '1999', 'category': 'Attar', 'image': 'assets/images/qissa-12ml-rs-1999.jpeg'},
    {'id': 71, 'name': 'Sewaaj', 'price': '1399', 'category': 'Attar', 'image': 'assets/images/sewaaj-12ml-rs-1399.jpeg'},
    {'id': 72, 'name': 'Shamamat Ul Amber', 'price': '4999', 'category': 'Attar', 'image': 'assets/images/shamamat-ul-amber-12ml-rs-4999.jpeg'},
    {'id': 73, 'name': 'Sheikh Ul Haramain', 'price': '1599', 'category': 'Attar', 'image': 'assets/images/sheikh-ul-haramain-12ml-rs-1599.jpeg'},
    {'id': 74, 'name': 'Rashaa', 'price': '1299', 'category': 'Attar', 'image': 'assets/images/rashaa-12ml-rs-1299.jpeg'},
    {'id': 75, 'name': 'Rasmi', 'price': '1999', 'category': 'Attar', 'image': 'assets/images/rasmi-20ml-rs-1999.jpeg'},
    {'id': 76, 'name': 'Sigaar', 'price': '1599', 'category': 'Attar', 'image': 'assets/images/sigaar-12ml-rs-1599.jpeg'},
    {'id': 77, 'name': 'Tara', 'price': '1399', 'category': 'Attar', 'image': 'assets/images/tara-12ml-rs-1399.jpeg'},
    {'id': 78, 'name': 'Tiger', 'price': '1199', 'category': 'Attar', 'image': 'assets/images/tiger-12ml-rs-1199.jpeg'},
    {'id': 79, 'name': 'White Oud 12ml', 'price': '1399', 'category': 'Attar', 'image': 'assets/images/white-oud-12ml-rs-1399.jpeg'},
    {'id': 80, 'name': 'Zarar', 'price': '1299', 'category': 'Attar', 'image': 'assets/images/zarar-12ml-rs-1299.jpeg'},
    {'id': 81, 'name': 'Ali Asghar', 'price': '799', 'category': 'Body Spray', 'image': 'assets/images/ali-asghar-rs-799.jpeg'},
    {'id': 82, 'name': 'Blue Lady By Rasasi', 'price': '799', 'category': 'Body Spray', 'image': 'assets/images/blue-lady-by-rasasi-rs-799.jpeg'},
    {'id': 83, 'name': 'Body Spray By J.', 'price': '899', 'category': 'Body Spray', 'image': 'assets/images/body-spray-by-j.-.jpeg'},
    {'id': 84, 'name': 'Body Spray By Lattafa', 'price': '950', 'category': 'Body Spray', 'image': 'assets/images/body-spray-by-lattafa-rs-950.jpeg'},
    {'id': 85, 'name': 'Body Spray', 'price': '850', 'category': 'Body Spray', 'image': 'assets/images/body-spray-rs-850.jpeg'},
    {'id': 86, 'name': 'Fogg Body Spray', 'price': '799', 'category': 'Body Spray', 'image': 'assets/images/fogg-rs-799.jpeg'},
    {'id': 87, 'name': 'Janan Sport By J.', 'price': '899', 'category': 'Body Spray', 'image': 'assets/images/janan-sport-by-j.-rs-899.jpeg'},
    {'id': 88, 'name': 'Khumar By J.', 'price': '899', 'category': 'Body Spray', 'image': 'assets/images/khumar-by-j.-rs-899.jpeg'},
    {'id': 89, 'name': 'Room Freshner', 'price': '850', 'category': 'Body Spray', 'image': 'assets/images/room-freshner-rs-850.jpeg'},
    {'id': 90, 'name': 'White Musk By J.', 'price': '899', 'category': 'Body Spray', 'image': 'assets/images/white-musk-by-j.--rs-899.jpeg'}
]

def gen_card(p):
    return f'''                    <div class="product-card" style="min-width: 220px; max-width: 220px; height: 320px; border-radius: 14px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); overflow: hidden; flex-shrink: 0; background: #f9f9f9; display: flex; flex-direction: column; position: relative; scroll-snap-align: start; transition: 0.3s;" onmouseover="this.querySelector('.hover-btn').style.opacity='1'; this.querySelector('.hover-btn').style.transform='translateY(0)';" onmouseout="this.querySelector('.hover-btn').style.opacity='0'; this.querySelector('.hover-btn').style.transform='translateY(10px)';" data-category="{p['category']}">
                        <img src="{p['image']}" style="width: 100%; height: 200px; object-fit: cover;" alt="{p['name']}">
                        <div style="padding: 15px;">
                            <p style="font-size:15px; font-weight:700; color:#333; margin: 0;">{p['name']}</p>
                            <p style="font-size:14px; color:#D4AF37; font-weight: 700; margin-top: 5px;">Rs. {p['price']}</p>
                        </div>
                        <div class="hover-btn" style="position: absolute; bottom: 15px; left: 10px; right: 10px; opacity: 0; transform: translateY(10px); transition: 0.3s;">
                            <button onclick="addToCart('{p['name']}')" style="width: 100%; padding: 10px; background: #000; color: #fff; border: none; border-radius: 8px; cursor: pointer; font-weight: 700; font-size: 11px; text-transform: uppercase; letter-spacing: 1px;">Add To Cart</button>
                        </div>
                    </div>'''

html = '\n'.join([gen_card(p) for p in products])
with open('products_html.txt', 'w', encoding='utf-8') as f:
    f.write(html)
